### ISSUE TITLE
FE path and config.absRefPrefix

### ISSUE THREAD

**Issue by gaumondp** [svewap/context_ribbon#1]
Great extension !

It looks like the extension doesn't use config.absRefPrefix ? My test site is under two subdirectories : 

`
config.absRefPrefix = /manyt3/one/`

The FE works for other JS and CSS but those for "ribbon" are written like this in the HTML source :  

```
<link rel="stylesheet" type="text/css" href="../typo3conf/ext/context_ribbon//Resources/Public/CSS/ribbon.css" media="all" />
<script src="../typo3conf/ext/context_ribbon//Resources/Public/JavaScript/ribbon.js" type="text/javascript"></script>
```

So we got 404s instead of seeing the small ribbon in FE. No problem in BE using TYPO3 7.6.

**Comment by svewap** [comment]
Fixed in version 1.0.4
